apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: polyempire

resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml

# Uncomment and configure if you want to use different image tags
# images:
#   - name: polyempire
#     newTag: v1.0.0

